name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Tests:
    defaults:
      run:
        working-directory: ./backend/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: execute gradlew
        run: ./gradlew test